// Package database provides database initialization, migration, and management utilities
// for the xui-im panel using GORM with PostgreSQL.
package database

import (
	"bytes"
	"errors"
	"fmt"
	"log"
	"os"
	"os/exec"
	"slices"
	"strings"

	"github.com/codewithtamim/xui-im/v2/config"
	"github.com/codewithtamim/xui-im/v2/database/model"
	"github.com/codewithtamim/xui-im/v2/util/crypto"
	"github.com/codewithtamim/xui-im/v2/xray"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

var db *gorm.DB

const (
	defaultUsername = "admin"
	defaultPassword = "admin"
)

func initModels() error {
	models := []any{
		&model.User{},
		&model.Inbound{},
		&model.OutboundTraffics{},
		&model.Setting{},
		&model.InboundClientIps{},
		&xray.ClientTraffic{},
		&model.HistoryOfSeeders{},
		&model.ApiKey{},
		&model.CustomGeoResource{},
	}
	for _, model := range models {
		if err := db.AutoMigrate(model); err != nil {
			log.Printf("Error auto migrating model: %v", err)
			return err
		}
	}
	return nil
}

// initUser creates a default admin user if the users table is empty.
func initUser() error {
	empty, err := isTableEmpty("users")
	if err != nil {
		log.Printf("Error checking if users table is empty: %v", err)
		return err
	}
	if empty {
		hashedPassword, err := crypto.HashPasswordAsBcrypt(defaultPassword)

		if err != nil {
			log.Printf("Error hashing default password: %v", err)
			return err
		}

		user := &model.User{
			Username: defaultUsername,
			Password: hashedPassword,
		}
		return db.Create(user).Error
	}
	return nil
}

// runSeeders migrates user passwords to bcrypt and records seeder execution to prevent re-running.
func runSeeders(isUsersEmpty bool) error {
	empty, err := isTableEmpty("history_of_seeders")
	if err != nil {
		log.Printf("Error checking if users table is empty: %v", err)
		return err
	}

	if empty && isUsersEmpty {
		hashSeeder := &model.HistoryOfSeeders{
			SeederName: "UserPasswordHash",
		}
		return db.Create(hashSeeder).Error
	} else {
		var seedersHistory []string
		db.Model(&model.HistoryOfSeeders{}).Pluck("seeder_name", &seedersHistory)

		if !slices.Contains(seedersHistory, "UserPasswordHash") && !isUsersEmpty {
			var users []model.User
			db.Find(&users)

			for _, user := range users {
				hashedPassword, err := crypto.HashPasswordAsBcrypt(user.Password)
				if err != nil {
					log.Printf("Error hashing password for user '%s': %v", user.Username, err)
					return err
				}
				db.Model(&user).Update("password", hashedPassword)
			}

			hashSeeder := &model.HistoryOfSeeders{
				SeederName: "UserPasswordHash",
			}
			return db.Create(hashSeeder).Error
		}
	}

	return nil
}

// isTableEmpty returns true if the named table contains zero rows.
func isTableEmpty(tableName string) (bool, error) {
	var count int64
	err := db.Table(tableName).Count(&count).Error
	return count == 0, err
}

// InitDB sets up the PostgreSQL database connection, migrates models, and runs seeders.
func InitDB(dsn string) error {
	var gormLogger logger.Interface

	if config.IsDebug() {
		gormLogger = logger.Default
	} else {
		gormLogger = logger.Discard
	}

	c := &gorm.Config{
		Logger: gormLogger,
	}

	var err error
	db, err = gorm.Open(postgres.Open(dsn), c)
	if err != nil {
		return err
	}

	if err := initModels(); err != nil {
		return err
	}

	isUsersEmpty, err := isTableEmpty("users")
	if err != nil {
		return err
	}

	if err := initUser(); err != nil {
		return err
	}
	return runSeeders(isUsersEmpty)
}

// CloseDB closes the database connection if it exists.
func CloseDB() error {
	if db != nil {
		sqlDB, err := db.DB()
		if err != nil {
			return err
		}
		return sqlDB.Close()
	}
	return nil
}

// GetDB returns the global GORM database instance.
func GetDB() *gorm.DB {
	return db
}

func IsNotFound(err error) bool {
	return errors.Is(err, gorm.ErrRecordNotFound)
}

// GenerateSQLDump generates a SQL dump of the current PostgreSQL database
// by executing pg_dump. If pg_dump is not found, falls back to querying
// tables directly via GORM.
func GenerateSQLDump() ([]byte, error) {
	host, port, user, password, dbname := config.GetPostgresEnv()

	cmd := exec.Command("pg_dump",
		"-h", host,
		"-p", port,
		"-U", user,
		"-d", dbname,
		"--no-owner",
		"--no-acl",
		"--clean",
		"--if-exists",
	)
	cmd.Env = append(os.Environ(), fmt.Sprintf("PGPASSWORD=%s", password))

	out, err := cmd.Output()
	if err != nil {
		return generateSQLDumpFallback()
	}
	return out, nil
}

// generateSQLDumpFallback generates a SQL dump by querying tables directly
// via GORM. Used when pg_dump is not available.
func generateSQLDumpFallback() ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("-- SQL dump generated by xui-im\n\n")

	tableModels := []struct {
		table string
		ptr   any
	}{
		{"users", &[]model.User{}},
		{"inbounds", &[]model.Inbound{}},
		{"outbound_traffics", &[]model.OutboundTraffics{}},
		{"settings", &[]model.Setting{}},
		{"inbound_client_ips", &[]model.InboundClientIps{}},
		{"client_traffics", &[]xray.ClientTraffic{}},
		{"history_of_seeders", &[]model.HistoryOfSeeders{}},
		{"api_keys", &[]model.ApiKey{}},
		{"custom_geo_resources", &[]model.CustomGeoResource{}},
	}

	for _, m := range tableModels {
		buf.WriteString(fmt.Sprintf("DELETE FROM %s;\n", m.table))

		rows, err := db.Table(m.table).Rows()
		if err != nil {
			log.Printf("Error reading rows from %s: %v", m.table, err)
			continue
		}

		cols, err := rows.Columns()
		if err != nil {
			rows.Close()
			continue
		}

		var rowData []map[string]any
		for rows.Next() {
			values := make([]any, len(cols))
			valuePtrs := make([]any, len(cols))
			for i := range cols {
				valuePtrs[i] = &values[i]
			}

			if err := rows.Scan(valuePtrs...); err != nil {
				continue
			}
			row := make(map[string]any)
			for i, col := range cols {
				row[col] = values[i]
			}
			rowData = append(rowData, row)
		}
		rows.Close()

		for _, row := range rowData {
			var colNames []string
			var colValues []string
			for col, val := range row {
				colNames = append(colNames, col)
				if val == nil {
					colValues = append(colValues, "NULL")
				} else {
					colValues = append(colValues, fmt.Sprintf("'%v'", strings.ReplaceAll(fmt.Sprintf("%v", val), "'", "''")))
				}
			}
			buf.WriteString(fmt.Sprintf("INSERT INTO %s (%s) VALUES (%s);\n",
				m.table,
				strings.Join(colNames, ", "),
				strings.Join(colValues, ", ")))
		}
		buf.WriteString("\n")
	}
	return buf.Bytes(), nil
}

// ExecuteSQLDump executes SQL statements from a dump file.
func ExecuteSQLDump(data []byte) error {
	return db.Exec(string(data)).Error
}
